{% set name = "tidygraphtool" %}
{% set version = "0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d03aaee8dc6f0ef011994ce1bd81f2f1538be3d961241e5d1cec33b5d756866c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - graph-tool
    - pandas
    - numpy==1.16

test:
  imports:
    - tidygraphtool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jstonge/tidygraphtool
  summary: A tidy API for network manipulation with Graph-tool inspired by tidygraph.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - https://github.com/jstonge
